# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a83376857c8b8dd360c04b73c23e0cc5d34af47f77ab4a402c4065a4456fd7b6248976dec446e06c0c77d9e47a3db562896dbd862360aef6644dd6200be90349

test:
  secret_key_base: 16323b3b4089acc2ec93b56b27e34cc558a1fde3413604898d1d7232909ab1e07857e087ffee7b1bca90c9a9709e14110272dd2e5eebb65ce349fa03cf0b9131

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
